Homework 2
================
Karthika Shankar
2026-10-07

# Problem 1

``` r
subway_df = 
  read_csv(
    
  "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(
      Route8 = col_character(),
      Route9 = col_character(),
      Route10 = col_character(),
      Route11 = col_character()
    )
  ) |>
  janitor::clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

The subway dataset includes information about subway stations and their
entrances and exits like the station name, line, location, routes
served, entrance type, vending availability, and ADA accessibility. I
cleaned the variable names, kept only the variables needed for this
problem, and changed the `entry` variable from “YES” and “NO” to a
logical variable. The cleaned dataset has 1868 rows and 19 columns. The
data are not tidy because the routes are spread across many different
columns (`route1` through `route11`) instead of being stored in one
route variable.

``` r
subway_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct subway stations in the dataset.

``` r
subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

There are 84 ADA-compliant subway stations in the dataset.

``` r
subway_df |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

    ## [1] 0.3770492

Among station entrances and exits without vending about 37.7% allow
entrance.

``` r
subway_tidy_df =
  subway_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) |>
  drop_na(route_name)
```

``` r
subway_tidy_df |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

There are 60 distinct subway stations that serve the A train.

``` r
subway_tidy_df |>
  filter(route_name == "A" & ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

Of the stations that serve the A train 17 are ADA compliant.

# Problem 2

``` r
mr_trash_df =
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.factor(year),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )
```

``` r
professor_trash_df =
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    na = c("", "dive")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.factor(year),
    trash_wheel = "Professor Trash Wheel"
  )
```

``` r
gwynnda_df =
  readxl::read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.factor(year),
    trash_wheel = "Gwynnda"
  )
```

``` r
trash_wheel_df =
  bind_rows(
    mr_trash_df,
    professor_trash_df,
    gwynnda_df
  )
```

``` r
professor_weight =
  trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  pull(weight_tons) |>
  sum(na.rm = TRUE)

gwynnda_cigarettes =
  trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    month == "June",
    year == "2022"
  ) |>
  pull(cigarette_butts) |>
  sum(na.rm = TRUE)
```

``` r
nrow(trash_wheel_df)
```

    ## [1] 1269

``` r
professor_weight
```

    ## [1] 294.96

``` r
gwynnda_cigarettes
```

    ## [1] 18120

The combined Trash Wheel dataset has 1269 observations from Mr. Trash
Wheel, Professor Trash Wheel, and Gwynnda. The dataset includes
information like the dumpster number, month and year, weight and volume
of trash collected, cigarette butts, plastic bottles, and other types of
waste. I added a `trash_wheel` variable so it is easy to see which wheel
each observation came from. Professor Trash Wheel collected 294.96 tons
of trash in total, and Gwynnda collected 18,120 cigarette butts in June
2022.

# Problem 3

``` r
mci_baseline_df =
  read_csv(
    "./data/MCI_baseline.csv",
    skip = 1,
    na = "."
  ) |>
  janitor::clean_names()
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline_df =
  mci_baseline_df |>
  mutate(
    sex =
      case_match(
        sex,
        1 ~ "male",
        0 ~ "female"
      ),
    sex = as.factor(sex),
    apoe4 =
      case_match(
        apoe4,
        1 ~ "carrier",
        0 ~ "non-carrier"
      ),
    apoe4 = as.factor(apoe4)
  ) |>
  filter(
    is.na(age_at_onset) | age_at_onset > current_age
  )
```

``` r
number_recruited =
  nrow(mci_baseline_df)

number_developed_mci =
  mci_baseline_df |>
  drop_na(age_at_onset) |>
  nrow()

average_baseline_age =
  mci_baseline_df |>
  pull(current_age) |>
  mean()

women_apoe4 =
  mci_baseline_df |>
  filter(sex == "female") |>
  mutate(apoe4_carrier = apoe4 == "carrier") |>
  pull(apoe4_carrier) |>
  mean()
```

``` r
number_recruited
```

    ## [1] 479

``` r
number_developed_mci
```

    ## [1] 93

``` r
average_baseline_age
```

    ## [1] 65.0286

``` r
women_apoe4
```

    ## [1] 0.3

The baseline dataset originally had 483 participants and included
information on age, sex, education, APOE4 status, and age at MCI onset.
I skipped the first descriptive row and treated “.” as a missing value
when importing the data. I changed sex and APOE4 status into categorical
variables and removed participants who already had MCI at baseline.
After cleaning, 479 participants were left and 93 of them developed MCI
during follow-up. The average baseline age was 65.03 years and 30% of
the women were APOE4 carriers.

``` r
mci_amyloid_df =
  read_csv(
    "./data/mci_amyloid.csv",
    skip = 1,
    na = c(".", "NA", "", "Na")
  ) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(
    baseline:time_8,
    names_to = "visit",
    values_to = "amyloid"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The amyloid dataset includes measurements from baseline and several
follow-up visits. I skipped the first descriptive row, cleaned the
variable names, handled the missing values, and used `pivot_longer()` to
organize the repeated amyloid measurements.

``` r
baseline_only =
  mci_baseline_df |>
  distinct(id) |>
  left_join(
    mci_amyloid_df |>
      distinct(id) |>
      mutate(in_amyloid = TRUE),
    by = "id"
  ) |>
  filter(is.na(in_amyloid))

amyloid_only =
  mci_amyloid_df |>
  distinct(id) |>
  left_join(
    mci_baseline_df |>
      distinct(id) |>
      mutate(in_baseline = TRUE),
    by = "id"
  ) |>
  filter(is.na(in_baseline))
```

``` r
nrow(baseline_only)
```

    ## [1] 8

``` r
nrow(amyloid_only)
```

    ## [1] 16

``` r
mci_df =
  inner_join(
    mci_baseline_df,
    mci_amyloid_df,
    by = "id"
  )
```

``` r
mci_df |>
  distinct(id) |>
  nrow()
```

    ## [1] 471

``` r
nrow(mci_df)
```

    ## [1] 2355

There are 8 participants who appear only in the baseline dataset and 16
who appear only in the amyloid dataset. After combining the datasets and
keeping only participants who appear in both, the final dataset has 471
participants and 2355 observations. The combined dataset includes the
baseline demographic information with each participant’s visit and
amyloid measurement.

``` r
write_csv(
  mci_df,
  "./data/mci_clean.csv"
)
```
